import type { Metadata } from "next";
import Link from "next/link";
import AdSlot from "@/components/layout/AdSlot";
import ToolLayout from "@/components/tools/ToolLayout";

const SITE_URL = "https://evmtools.dev";

export const metadata: Metadata = {
  title:
    "ABI Encoding Explained: How Ethereum Smart Contracts Communicate | EVMTools",
  description:
    "Understand how Ethereum ABI encoding works, from function selectors to parameter encoding. A complete guide for Solidity developers.",
  keywords: [
    "abi encoding",
    "abi encoder",
    "ethereum abi",
    "solidity abi",
    "abi decode",
    "what is abi encoding",
    "smart contract abi",
    "function selector",
    "calldata encoding",
  ],
  openGraph: {
    title:
      "ABI Encoding Explained: How Ethereum Smart Contracts Communicate | EVMTools",
    description:
      "Understand how Ethereum ABI encoding works, from function selectors to parameter encoding. A complete guide for Solidity developers.",
    url: `${SITE_URL}/guides/abi-encoding-explained`,
    siteName: "EVMTools",
    type: "article",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "ABI Encoding Explained: How Ethereum Smart Contracts Communicate",
    description:
      "Understand how Ethereum ABI encoding works, from function selectors to parameter encoding. A complete guide for Solidity developers.",
  },
  alternates: {
    canonical: `${SITE_URL}/guides/abi-encoding-explained`,
  },
};

export default function AbiEncodingExplainedPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline:
      "ABI Encoding Explained: How Ethereum Smart Contracts Communicate",
    description:
      "Understand how Ethereum ABI encoding works, from function selectors to parameter encoding. A complete guide for Solidity developers.",
    url: `${SITE_URL}/guides/abi-encoding-explained`,
    publisher: {
      "@type": "Organization",
      name: "EVMTools",
      url: SITE_URL,
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `${SITE_URL}/guides/abi-encoding-explained`,
    },
  };

  return (
    <ToolLayout slug="abi-encoding-explained">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <article className="prose-custom space-y-8">
        {/* Intro */}
        <section className="space-y-4">
          <p className="text-lg leading-relaxed text-gray-300">
            Every time you interact with an Ethereum smart contract &mdash;
            whether you are transferring tokens, swapping on a DEX, or minting
            an NFT &mdash; your transaction contains a blob of hexadecimal data
            called ABI-encoded calldata. Understanding ABI encoding is essential
            for any Ethereum developer who wants to debug transactions, build
            integrations, or write low-level Solidity code.
          </p>
        </section>

        {/* What is ABI? */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">What is ABI?</h2>
          <p className="leading-relaxed text-gray-300">
            ABI stands for{" "}
            <strong className="text-white">
              Application Binary Interface
            </strong>
            . In the context of Ethereum, the ABI defines how data is encoded
            and decoded when communicating with smart contracts. Think of it as a
            contract&apos;s API specification: it tells callers what functions are
            available, what parameters they accept, and what data they return.
          </p>
          <p className="leading-relaxed text-gray-300">
            An ABI is typically represented as a JSON array that describes all
            public and external functions, events, and errors in a contract:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`[
  {
    "type": "function",
    "name": "transfer",
    "inputs": [
      { "name": "to", "type": "address" },
      { "name": "amount", "type": "uint256" }
    ],
    "outputs": [
      { "name": "", "type": "bool" }
    ]
  }
]`}</code>
          </pre>
          <p className="leading-relaxed text-gray-300">
            This JSON is generated by the Solidity compiler and is used by
            libraries like ethers.js and web3.js to encode function calls into
            the raw bytes that the EVM understands.
          </p>
        </section>

        {/* How ABI Encoding Works */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">
            How ABI Encoding Works
          </h2>
          <p className="leading-relaxed text-gray-300">
            When you call a smart contract function, the transaction&apos;s input
            data (calldata) is structured as follows:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`[4-byte function selector] [32-byte encoded parameter 1] [32-byte encoded parameter 2] ...`}</code>
          </pre>

          <h3 className="text-xl font-semibold text-white">
            Step 1: Function Selector
          </h3>
          <p className="leading-relaxed text-gray-300">
            The function selector is the first 4 bytes of the Keccak256 hash of
            the function&apos;s canonical signature. The canonical signature
            includes the function name and parameter types, with no spaces.
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`Function: transfer(address,uint256)
Keccak256: 0xa9059cbb2ab09eb219583f4a59a5d0623ade346d962bcd4e46b11da047c9049b
Selector:  0xa9059cbb (first 4 bytes)`}</code>
          </pre>
          <p className="leading-relaxed text-gray-300">
            This compact representation lets the EVM quickly identify which
            function to execute without needing the full function name. You can
            compute function selectors using our{" "}
            <Link
              href="/crypto/keccak256-hash"
              className="text-blue-400 underline decoration-blue-400/30 hover:decoration-blue-400"
            >
              Keccak256 Hash Generator
            </Link>
            .
          </p>

          <h3 className="text-xl font-semibold text-white">
            Step 2: Parameter Encoding
          </h3>
          <p className="leading-relaxed text-gray-300">
            After the selector, each parameter is encoded according to its
            Solidity type. The ABI specification divides types into two
            categories:
          </p>

          <h3 className="text-lg font-semibold text-gray-200">Static Types</h3>
          <p className="leading-relaxed text-gray-300">
            Static types have a fixed size and are encoded directly in place,
            always padded to 32 bytes.
          </p>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-gray-700">
                  <th className="px-4 py-3 font-semibold text-gray-200">
                    Type
                  </th>
                  <th className="px-4 py-3 font-semibold text-gray-200">
                    Size
                  </th>
                  <th className="px-4 py-3 font-semibold text-gray-200">
                    Encoding Rule
                  </th>
                </tr>
              </thead>
              <tbody className="text-gray-400">
                <tr className="border-b border-gray-800">
                  <td className="px-4 py-3">
                    <code className="text-amber-400">uint256</code>
                  </td>
                  <td className="px-4 py-3">32 bytes</td>
                  <td className="px-4 py-3">Left-padded with zeros</td>
                </tr>
                <tr className="border-b border-gray-800">
                  <td className="px-4 py-3">
                    <code className="text-amber-400">int256</code>
                  </td>
                  <td className="px-4 py-3">32 bytes</td>
                  <td className="px-4 py-3">
                    Two&apos;s complement, left-padded
                  </td>
                </tr>
                <tr className="border-b border-gray-800">
                  <td className="px-4 py-3">
                    <code className="text-amber-400">address</code>
                  </td>
                  <td className="px-4 py-3">20 bytes</td>
                  <td className="px-4 py-3">Left-padded to 32 bytes</td>
                </tr>
                <tr className="border-b border-gray-800">
                  <td className="px-4 py-3">
                    <code className="text-amber-400">bool</code>
                  </td>
                  <td className="px-4 py-3">1 byte</td>
                  <td className="px-4 py-3">
                    <code className="text-amber-400">0x01</code> for true,{" "}
                    <code className="text-amber-400">0x00</code> for false,
                    left-padded
                  </td>
                </tr>
                <tr>
                  <td className="px-4 py-3">
                    <code className="text-amber-400">bytes32</code>
                  </td>
                  <td className="px-4 py-3">32 bytes</td>
                  <td className="px-4 py-3">Right-padded with zeros</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3 className="text-lg font-semibold text-gray-200">
            Dynamic Types
          </h3>
          <p className="leading-relaxed text-gray-300">
            Dynamic types (
            <code className="rounded bg-gray-800 px-1.5 py-0.5 text-sm text-amber-400">
              string
            </code>
            ,{" "}
            <code className="rounded bg-gray-800 px-1.5 py-0.5 text-sm text-amber-400">
              bytes
            </code>
            ,{" "}
            <code className="rounded bg-gray-800 px-1.5 py-0.5 text-sm text-amber-400">
              uint256[]
            </code>
            , etc.) use indirect encoding with an offset pointer:
          </p>
          <ol className="ml-6 list-decimal space-y-2 text-gray-300">
            <li>
              In the parameter&apos;s position, write a 32-byte offset pointing
              to where the actual data begins.
            </li>
            <li>
              At that offset, write the length of the data followed by the data
              itself.
            </li>
          </ol>
          <p className="leading-relaxed text-gray-300">
            This system allows the decoder to know exactly where each
            parameter&apos;s data lives, regardless of how large the dynamic
            data is.
          </p>
        </section>

        {/* Complete Example */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">Complete Example</h2>
          <p className="leading-relaxed text-gray-300">
            Let&apos;s encode a call to{" "}
            <code className="rounded bg-gray-800 px-1.5 py-0.5 text-sm text-amber-400">
              transfer(address,uint256)
            </code>{" "}
            with these parameters:
          </p>
          <ul className="ml-6 list-disc space-y-1 text-gray-300">
            <li>
              <strong className="text-white">to</strong>:{" "}
              <code className="rounded bg-gray-800 px-1.5 py-0.5 text-sm text-amber-400">
                0xAbCdEf0123456789AbCdEf0123456789AbCdEf01
              </code>
            </li>
            <li>
              <strong className="text-white">amount</strong>:{" "}
              <code className="rounded bg-gray-800 px-1.5 py-0.5 text-sm text-amber-400">
                1000000000000000000
              </code>{" "}
              (1 ETH in Wei)
            </li>
          </ul>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`Function selector:
  a9059cbb

Parameter 1 (address, padded to 32 bytes):
  000000000000000000000000abcdef0123456789abcdef0123456789abcdef01

Parameter 2 (uint256, 32 bytes):
  0000000000000000000000000000000000000000000000000de0b6b3a7640000

Full calldata:
  0xa9059cbb
    000000000000000000000000abcdef0123456789abcdef0123456789abcdef01
    0000000000000000000000000000000000000000000000000de0b6b3a7640000`}</code>
          </pre>
          <p className="leading-relaxed text-gray-300">
            You can verify this encoding using our{" "}
            <Link
              href="/crypto/abi-encoder"
              className="text-blue-400 underline decoration-blue-400/30 hover:decoration-blue-400"
            >
              ABI Encoder/Decoder
            </Link>{" "}
            &mdash; enter the function signature and the parameters to see the
            encoded result.
          </p>
        </section>

        <AdSlot slotId="guide-mid-1" format="auto" className="my-8" />

        {/* Dynamic Type Encoding */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">
            Dynamic Type Encoding: A Deeper Look
          </h2>
          <p className="leading-relaxed text-gray-300">
            Dynamic types are more complex. Let&apos;s encode a call to a
            function with a dynamic array:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`function batchTransfer(address[] calldata recipients, uint256 amount)`}</code>
          </pre>
          <p className="leading-relaxed text-gray-300">
            With{" "}
            <code className="rounded bg-gray-800 px-1.5 py-0.5 text-sm text-amber-400">
              recipients = [0xAAA..., 0xBBB...]
            </code>{" "}
            and{" "}
            <code className="rounded bg-gray-800 px-1.5 py-0.5 text-sm text-amber-400">
              amount = 100
            </code>
            :
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`Selector: (4 bytes)

Offset to recipients array:   0x0000...0040  (64 bytes from start of params)
amount (static, in-place):    0x0000...0064  (100 in hex)

--- At offset 64 ---
Array length:                 0x0000...0002  (2 elements)
Element 1 (address):          0x0000...0AAA...
Element 2 (address):          0x0000...0BBB...`}</code>
          </pre>
          <p className="leading-relaxed text-gray-300">
            The key insight is that static parameters are encoded in-place, while
            dynamic parameters leave an offset pointer and store the actual data
            at the end of the parameter block.
          </p>
        </section>

        {/* ABI Encoding in Practice */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">
            ABI Encoding in Practice
          </h2>

          <h3 className="text-xl font-semibold text-white">
            Using ethers.js
          </h3>
          <p className="leading-relaxed text-gray-300">
            The most common way to work with ABI encoding in JavaScript is
            through ethers.js:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`import { AbiCoder, keccak256, toUtf8Bytes } from 'ethers';

const coder = AbiCoder.defaultAbiCoder();

// Encode parameters
const encoded = coder.encode(
  ['address', 'uint256'],
  ['0xAbCdEf0123456789AbCdEf0123456789AbCdEf01', '1000000000000000000']
);

// Decode parameters
const decoded = coder.decode(
  ['address', 'uint256'],
  encoded
);
console.log(decoded[0]); // 0xAbCdEf0123456789AbCdEf0123456789AbCdEf01
console.log(decoded[1]); // 1000000000000000000n (BigInt)`}</code>
          </pre>

          <h3 className="text-xl font-semibold text-white">Using Solidity</h3>
          <p className="leading-relaxed text-gray-300">
            Solidity provides built-in functions for ABI encoding:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`// Standard encoding (each param padded to 32 bytes)
bytes memory data = abi.encode(addr, amount);

// Packed encoding (no padding, tightly packed)
bytes memory packed = abi.encodePacked(addr, amount);

// Encode a function call (selector + params)
bytes memory callData = abi.encodeWithSignature(
    "transfer(address,uint256)",
    recipient,
    amount
);

// Encode with a known selector
bytes memory callData = abi.encodeWithSelector(
    IERC20.transfer.selector,
    recipient,
    amount
);

// Decode
(address to, uint256 amt) = abi.decode(data, (address, uint256));`}</code>
          </pre>

          <h3 className="text-xl font-semibold text-white">
            abi.encode vs abi.encodePacked
          </h3>
          <p className="leading-relaxed text-gray-300">
            This is a frequent source of confusion. The two functions produce
            very different outputs:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`abi.encode(uint8(1), uint8(2))
// 0x0000...0001 0000...0002
// (64 bytes: each value padded to 32 bytes)

abi.encodePacked(uint8(1), uint8(2))
// 0x0102
// (2 bytes: values concatenated without padding)`}</code>
          </pre>

          <p className="leading-relaxed text-gray-300">
            <strong className="text-white">When to use which:</strong>
          </p>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-gray-700">
                  <th className="px-4 py-3 font-semibold text-gray-200">
                    Use Case
                  </th>
                  <th className="px-4 py-3 font-semibold text-gray-200">
                    Function
                  </th>
                  <th className="px-4 py-3 font-semibold text-gray-200">
                    Why
                  </th>
                </tr>
              </thead>
              <tbody className="text-gray-400">
                <tr className="border-b border-gray-800">
                  <td className="px-4 py-3">Calling contract functions</td>
                  <td className="px-4 py-3">
                    <code className="text-amber-400">abi.encode</code>
                  </td>
                  <td className="px-4 py-3">Standard ABI format required</td>
                </tr>
                <tr className="border-b border-gray-800">
                  <td className="px-4 py-3">Hashing for signatures</td>
                  <td className="px-4 py-3">
                    <code className="text-amber-400">abi.encode</code>
                  </td>
                  <td className="px-4 py-3">
                    Avoids collision vulnerabilities
                  </td>
                </tr>
                <tr className="border-b border-gray-800">
                  <td className="px-4 py-3">Merkle tree leaves</td>
                  <td className="px-4 py-3">
                    <code className="text-amber-400">abi.encodePacked</code>
                  </td>
                  <td className="px-4 py-3">
                    More gas efficient, but use carefully
                  </td>
                </tr>
                <tr>
                  <td className="px-4 py-3">Data storage</td>
                  <td className="px-4 py-3">
                    <code className="text-amber-400">abi.encode</code>
                  </td>
                  <td className="px-4 py-3">Easier to decode later</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <AdSlot slotId="guide-mid-2" format="auto" className="my-8" />

        {/* Reading ABI-Encoded Data on Etherscan */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">
            Reading ABI-Encoded Data on Etherscan
          </h2>
          <p className="leading-relaxed text-gray-300">
            When you look at a transaction on Etherscan and click &quot;Decode
            Input Data,&quot; Etherscan is performing ABI decoding. If the
            contract&apos;s ABI is verified, Etherscan can show you
            human-readable parameter names and values.
          </p>
          <p className="leading-relaxed text-gray-300">
            But what if the contract is not verified? You can still decode the
            calldata manually:
          </p>
          <ol className="ml-6 list-decimal space-y-2 text-gray-300">
            <li>
              Take the first 4 bytes &mdash; that is the function selector
            </li>
            <li>
              Look up the selector in a database like 4byte.directory
            </li>
            <li>
              Once you know the function signature, decode the remaining bytes
              according to the parameter types
            </li>
          </ol>
          <p className="leading-relaxed text-gray-300">
            Or simply paste the encoded data into our{" "}
            <Link
              href="/crypto/abi-encoder"
              className="text-blue-400 underline decoration-blue-400/30 hover:decoration-blue-400"
            >
              ABI Encoder/Decoder
            </Link>{" "}
            and let it handle the decoding for you.
          </p>
        </section>

        {/* Common ABI Encoding Patterns */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">
            Common ABI Encoding Patterns
          </h2>

          <h3 className="text-xl font-semibold text-white">
            ERC-20 Token Transfers
          </h3>
          <p className="leading-relaxed text-gray-300">
            The most common ABI-encoded transaction on Ethereum:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`Selector: 0xa9059cbb (transfer)
Params:   [address recipient] [uint256 amount]`}</code>
          </pre>

          <h3 className="text-xl font-semibold text-white">
            ERC-20 Approvals
          </h3>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`Selector: 0x095ea7b3 (approve)
Params:   [address spender] [uint256 amount]`}</code>
          </pre>

          <h3 className="text-xl font-semibold text-white">
            Uniswap V2 Swaps
          </h3>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`Selector: 0x38ed1739 (swapExactTokensForTokens)
Params:   [uint256 amountIn] [uint256 amountOutMin] [address[] path]
          [address to] [uint256 deadline]`}</code>
          </pre>

          <h3 className="text-xl font-semibold text-white">Multicall</h3>
          <p className="leading-relaxed text-gray-300">
            Many DeFi protocols use multicall to batch multiple function calls
            into a single transaction:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`Selector: 0xac9650d8 (multicall)
Params:   [bytes[] data]  // Array of ABI-encoded function calls`}</code>
          </pre>
        </section>

        {/* Tuple and Error Encoding */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">Tuple Encoding</h2>
          <p className="leading-relaxed text-gray-300">
            Solidity structs are encoded as tuples in the ABI. A struct is
            treated as a sequence of its member types:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`struct Order {
    address maker;
    uint256 amount;
    uint256 price;
}

// ABI type for Order: (address,uint256,uint256)
// Encoded as: [address padded] [uint256] [uint256]`}</code>
          </pre>
          <p className="leading-relaxed text-gray-300">
            Nested structs create nested tuples:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`struct Trade {
    Order buyOrder;
    Order sellOrder;
    uint256 timestamp;
}

// ABI type: ((address,uint256,uint256),(address,uint256,uint256),uint256)`}</code>
          </pre>

          <h2 className="text-2xl font-bold text-white">Error Encoding</h2>
          <p className="leading-relaxed text-gray-300">
            Since Solidity 0.8.4, custom errors are also ABI-encoded using the
            same selector mechanism:
          </p>
          <pre className="overflow-x-auto rounded-lg bg-gray-800 p-4 text-sm leading-relaxed text-gray-200">
            <code>{`error InsufficientBalance(uint256 available, uint256 required);

// Selector: first 4 bytes of keccak256("InsufficientBalance(uint256,uint256)")
// Encoded: [selector] [available] [required]`}</code>
          </pre>
          <p className="leading-relaxed text-gray-300">
            When a transaction reverts with a custom error, the revert data
            contains the ABI-encoded error, which tools like ethers.js can decode
            to give you a meaningful error message.
          </p>
        </section>

        {/* FAQ */}
        <section className="space-y-6">
          <h2 className="text-2xl font-bold text-white">
            Frequently Asked Questions
          </h2>

          <div className="space-y-4 rounded-lg border border-gray-800 bg-gray-900 p-6">
            <h3 className="text-lg font-semibold text-white">
              What happens if I use the wrong ABI to decode data?
            </h3>
            <p className="leading-relaxed text-gray-300">
              You will get garbage values. The decoder will interpret the bytes
              according to the types you specified, which will produce incorrect
              results if the types do not match the actual encoding. Always use
              the correct ABI for the contract you are interacting with.
            </p>
          </div>

          <div className="space-y-4 rounded-lg border border-gray-800 bg-gray-900 p-6">
            <h3 className="text-lg font-semibold text-white">
              Can I ABI-encode data without knowing the full ABI?
            </h3>
            <p className="leading-relaxed text-gray-300">
              Yes, if you know the function signature (name and parameter types),
              you can encode and decode data. You do not need the full contract
              ABI &mdash; just the types of the parameters you are working with.
            </p>
          </div>

          <div className="space-y-4 rounded-lg border border-gray-800 bg-gray-900 p-6">
            <h3 className="text-lg font-semibold text-white">
              Why is ABI encoding 32-byte aligned?
            </h3>
            <p className="leading-relaxed text-gray-300">
              The EVM operates on 32-byte (256-bit) words. By aligning all data
              to 32 bytes, the ABI encoding matches the EVM&apos;s native word
              size, making it efficient to read and write data in the virtual
              machine.
            </p>
          </div>

          <div className="space-y-4 rounded-lg border border-gray-800 bg-gray-900 p-6">
            <h3 className="text-lg font-semibold text-white">
              Is ABI encoding the same across all EVM chains?
            </h3>
            <p className="leading-relaxed text-gray-300">
              Yes. ABI encoding is part of the EVM specification and is identical
              on Ethereum, Polygon, Arbitrum, Optimism, BSC, and all other
              EVM-compatible chains.
            </p>
          </div>
        </section>

        {/* CTA */}
        <section className="rounded-lg border border-blue-800/50 bg-blue-950/30 p-6">
          <h2 className="text-xl font-bold text-white">Try It Yourself</h2>
          <p className="mt-2 leading-relaxed text-gray-300">
            Want to encode or decode ABI data? Use our free{" "}
            <Link
              href="/crypto/abi-encoder"
              className="text-blue-400 underline decoration-blue-400/30 hover:decoration-blue-400"
            >
              ABI Encoder/Decoder
            </Link>{" "}
            to encode function calls or decode raw calldata directly in your
            browser.
          </p>
        </section>

        {/* Related Tools */}
        <section className="space-y-3 border-t border-gray-800 pt-6">
          <h2 className="text-lg font-semibold text-white">Related Tools</h2>
          <ul className="space-y-2 text-gray-300">
            <li>
              <Link
                href="/crypto/abi-encoder"
                className="text-blue-400 underline decoration-blue-400/30 hover:decoration-blue-400"
              >
                ABI Encoder/Decoder
              </Link>{" "}
              &mdash; Encode and decode smart contract calldata online
            </li>
            <li>
              <Link
                href="/crypto/keccak256-hash"
                className="text-blue-400 underline decoration-blue-400/30 hover:decoration-blue-400"
              >
                Keccak256 Hash Generator
              </Link>{" "}
              &mdash; Generate function selectors and hash data
            </li>
            <li>
              <Link
                href="/crypto/hex-decimal-converter"
                className="text-blue-400 underline decoration-blue-400/30 hover:decoration-blue-400"
              >
                Hex/Decimal Converter
              </Link>{" "}
              &mdash; Convert between hex and decimal values
            </li>
          </ul>
        </section>
      </article>
    </ToolLayout>
  );
}
